spring:
  datasource:
    username: "dbuser"
    password: "dbuser"
    url: "jdbc:postgresql://172.55.1.3/app"

  flyway:
    enabled: true

logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: "debug"

    com:
      amazonaws: "debug"

app:
  aws:
    client:
      credentials:
        accessKey: "s3key"
        secretKey: "s3secret"

      protocol: "HTTP"
      signerOverride: "AWSS3V4SignerType"
      pathStyleAccessEnabled: true
      uri: "s3://${app.aws.client.credentials.accessKey}@172.55.1.4:9000"

    bucket: "s3-default"

  filesystem:
    filesystems:
      -
        id: "${app.aws.bucket}"
        uri: "${app.aws.client.uri}"
      -
        id: "/"
        uri: "file:///"
