spring:
  datasource:
    username: "dbuser"
    password: "dbuser"
    url: "jdbc:postgresql://172.55.1.3/app"

  flyway:
    enabled: true

logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: "debug"

    com:
      amazonaws: "debug"

app:
  aws:
    credentials:
      accessKey: "s3key"
      secretKey: "s3secret"

    protocol: "HTTP"
    endpoint: "172.55.1.4:9000"
    signerOverride: "AWSS3V4SignerType"
    pathStyleAccessEnabled: true
