spring:
  application:
    name: "files"

  datasource:
    driver-class-name: "org.postgresql.Driver"

server:
  port: 8080

management:
  server:
    port: 8090

  endpoints:
    enabled-by-default: false

  endpoint:
    health:
      enabled: true
      probes:
        enabled: true

app:
  rest:
    api:
      prefix: "api"
      latest-version: "v1.0"

  aws:
    client:
      credentials:
        accessKey: "access key"
        secretKey: "secret key"

      protocol: "HTTPS"
      signerOverride: "AWSS3V4SignerType"
      pathStyleAccessEnabled: true
      uri: "s3://${app.aws.client.credentials.accessKey}@localhost"

    bucket: "s3-default"

  filesystem:
    filesystems:
      -
        id: "${app.aws.bucket}"
        uri: "${app.aws.client.uri}"
      -
        id: "/"
        uri: "file:///"
