spring:
  application:
    name: "claims"

  datasource:
    driver-class-name: "org.postgresql.Driver"

server:
  port: 8080

management:
  server:
    port: 8090

  endpoints:
    enabled-by-default: false

  endpoint:
    health:
      enabled: true
      probes:
        enabled: true

app:
  rest:
    api:
      prefix: "api"
      latest-version: "v1.0"
